version: '3.5'

services:
  laravel-app:
    build:
      context: .
      args:
        uid: ${UID}
    container_name: laravel-app
    ports:
      - 8080:80
    volumes:
      - ./laravel:/var/www/html/laravel
    networks:
      - backend

  mysql-db:
    # Si está utilizando una arquitectura x64, puede utilizar la imagen original de MySQL cambiando la línea de abajo a 'image: mysql:5.7.36'
    image: biarms/mysql:5.7
    container_name: mysql-db
    volumes:
      - ./run/var:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=securerootpassword
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    networks:
      - backend

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - 8081:8080
    networks:
      - backend

  nginx:
    image: nginx:latest
    container_name: laravel-nginx
    ports:
      - 8000:80
    volumes:
      - ./laravel:/var/www/html/laravel
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - backend

  node:
    image: node:16
    container_name: laravel-node
    volumes:
      - ./laravel:/var/www/html/laravel
    working_dir: /var/www/html/laravel
    networks:
      - backend
    command: "npm run watch"

networks:
  backend:
    name: backend-network
